### ISSUE TITLE
Potential jury scoring system

### ISSUE THREAD

**Issue by kronosapiens** [deepfunding/dependency-graph#1]
Here is a potential jury scoring system leveraging Pairwise. For context, I helped developed the BudgetBox technique and advised the Pairwise team during their early development.

## Problem Setup

![GewRTZXWgAAa2zN](https://github.com/user-attachments/assets/47090d42-c9c9-4ceb-86a5-b202f036057a)

We have a "depth 2" tree, with potentially large numbers of children per node. The goal is the production of a "probability distribution" (values summing to 1) across all nodes for every "depth 1" subtree of the graph.

Given the size of the problem, we leverage a competitive model-building community to produce results for all edges of the graph. Our goal is to check the correctness of the models against "spot-judgments" made by a jury of experts. Juries will be presented with pairs of dependencies and asked to make judgments along the lines of:

"Which of A or B deserves more credit for project X"

These judgments will be used to generate ground-truth probability distributions to score model submissions. The plan is to use the existing Pairwise implementation to help jurors in making these spot judgments.

## Judgment Criteria

The [specific criteria](https://x.com/TheDevanshMehta/status/1868031015522099392?t=OwOknt2cQhkYO_dDN-Qt7w&s=19) that the jurors should use in making their distinctions include:

1. Replaceability: How much time has the dependency saved you? 
2. Specificity: Is the dependency specific to EVM or a general building block like aes or hashes/nobles
3. Additionality: Is the dependency already well funded?

And potentially others.

## Scoring System

![IMG_6552 2](https://github.com/user-attachments/assets/5aaac078-58bb-44c5-add6-1adf8a94b646)

1. Divide the dependency tree into `k` subgraphs, each corresponding to a single project and its dependencies.
2. For every subgraph, create a fully-connected graph of all `n` dependencies and the project itself, so `n+1` nodes in total.
3. Treat every subgraph as a category in Pairwise, and present jurors with pairs drawn randomly from the subgraph.
4. Instruct jurors to set a slider somewhere between the pairs, answering the question of "What is the relative impact of the developer contributions of A vs B on project X".*
6. Use the collected edge weights to generate the training distribution for that subgraph and use it to score the models.
7. Repeat this process for as many of the subgraphs as needed to provide sufficient training and testing data for the model.

*By phrasing the question in terms of "developer contributions," the question remains valid for the question of a project vs its own dependency -- we are asking how much of the value of the project was provided by its own development team, vs that of a dependency's development team.

## Discussion

Some benefits of this approach:

- Limits spot-checking to a random subset of the `k` subgraphs.
- Leverages existing Pairwise functionality (IIRC all of this is currently supported)
- Allows jurors to contribute as little as one pair observation (O(1) complexity)
- As a consequence, allows for a large and highly distributed juror pool

Some downsides of this approach:

- Requires getting a density of votes for a chosen subgraph

Some strategies for achieving this density:

- A supplemental technique like [adaptive sampling](https://github.com/zaratanDotWorld/powerRanker/issues/2) could help converge more quickly on results
- Select projects with relatively small numbers of dependencies to use for training, and assume outputs generalize
- Leverage Pairwise's star system to group dependencies into "major" or "minor," reducing total number of pairs

Broadly, the goal is to to find ways to structure the sub-graph such that the total number of pairs is reduced from O(n^2) to O(n) as much as possible. For instance, splitting the graph in two (major vs minor) will cut the number of pairs nearly in half.

I think this approach fits within the constraints laid out by the project, but welcome feedback / discussion.

**Comment by JSeiferth** [comment]
On judgement criteria - I'd love to learn more about why these are the criteria.
> Replaceability: How much time has the dependency saved you?
> Specificity: Is the dependency specific to EVM or a general building block like aes or hashes/nobles
> Additionality: Is the dependency already well funded?


**On Judging process**
It seems like Jurors are expected to answer questions that are specific to a subgraph (e.g. a single project and its dependencies.). This could potentially be a very hard task considering there are hundreds of potential projects to judge. Here's a rough draft of the juror UX
1. Get familiar with the relevant codebase of the project in your assigned subgraph
2. Understand which dependency is more important to the project. 
3. Answer other questions such as EVM specificity or existing funding of dependencies

This could mean a lot of work for a juror to judge a single dependency. I assume we need to achieve some large sample size of judgements here, which seems hard if a single judgement requires a high time commitment. 

> Instruct jurors to set a slider somewhere between the pairs, answering the question of "What is the relative impact of the developer contributions of A vs B on project X".*

In practice, this could be a fairly complex task for a juror. We've seen from Retro Funding experiments that people struggle with these outright judgements. 

### Throwing out some ideas for how to make the judging process simpler
The overall risk I see is that the judging process becomes too complex, leading to low-quality output. I think part of the objective is to avoid psychological bias when making outright judgements. 
1. I would propose optimising for simple judging questions, that are either based on comparison or binary. 
2. Ask project maintainers about their dependencies, instead of random judges. Maintainers know their project best and they can give you a quick judgement if dependency A or dependency B is more important to them. AFAIK data from [Drips](https://www.drips.network/) will be used for this. 
3. Answer judging criteria separately to make the judging task simpler and reduce complexity: By isolating questions on specific criteria, like "Is the dependency specific to EVM or a general building block like aes or hashes/nobles?", you simplify the judging task and you get cleaner data. Judges could give you wildly different inputs if they interpret the criteria in different ways.

**Comment by kronosapiens** [comment]
Those are fair points. At a high level I would ask: if a single judgment provides a weak signal, would an aggregate of many provide a strong signal?

The criteria were suggested by @devansh76 and may be subject to change.

Some ways to simplify the problem would be to pull out the questions of funding level and specificity and address them elsewhere:

- Use current funding level as part of a post-processing step to scale the rewards amount up or down, rather than including it in the judgment decision.
- Use "specificity" to group dependencies together, i.e. "EVM dependencies," "Basic dependencies," etc and only compare items in those sets, reducing the number of total comparisons and making the comparisons more meaningful.

As far as making it easier for a judge to determine the relevance of a dependency to a project, it may be possible to scan the codebase and surface, for instance, the number of files the dependency was imported into. IIRC [SourceCred](https://sourcecred.io/) had some tooling for codebase dependency scanning, might be worth trying to integrate those as an additional signal.

**Comment by markoprljic** [comment]
@kronosapiens I mocked up the 5-point semantic scale for reference. 

<img width="1370" alt="Screenshot 2024-12-16 at 17 54 49" src="https://github.com/user-attachments/assets/870c2486-0ac3-44d8-b106-7c9187e55d67" />

**Comment by kronosapiens** [comment]
Another question I have: do we know a) how many jurors we are expecting to have and b) how long we expect jurors to spend on this task? Having estimates for those values would let us work backwards, i.e. 100 jurors x 2 hours = 200 hours / 5 seconds per pair = 144k pair-votes. If a single project has 100 dependencies bundled 50/50 into "high" and "low" importance, then that would give us ~2,500 pairs per project. Assuming we want 3 votes per pair for a strong result, then that means that we are able to get training data for 20 projects and use those to evaluate the models.

These are made-up numbers but I think give a sense for the problem. Does anyone else have more accurate numbers? Would be interesting to work through this and get a sense of what any bottlenecks might be.

**Comment by JSeiferth** [comment]
I think the following are the goals of the judging process
1. Collect accurate judgement data to train models
2. Achieve high judgement coverage across subgraphs

The more complex the judging task becomes, the less likely it is we will achieve either. We're also talking about a first MVP of deep funding, perfect is the enemy of good here. 

Here are some problems that I see: 
1. It requires a lot of effort for a judge to understand the importance of a particular dependency to a project that they're not familiar with 
2. It's hard for a judge to make outright judgements about the value of a dependency, even when using the slider (e.g. What percent of credit should go to dependency 1 vs dependency 2?)
3. Even maintainers struggle with rating their dependency. Diving into [Drips data](https://www.drips.network/app/projects/all), most maintainers fund a handful of dependencies with equal weight or with simple ranks. 

The risk is that by making the judging process more complex we actually get less accurate input. I think doing lots of testing here would be great. 

Here's some things we could test
1. Have one group do Pairwise comparison and another do outright comparison (e.g. slider). Collect data on time spent, number of comparison, values submitted, confidence in judgement etc.
2. Focus on one subgraph, have the maintainer judge their dependencies and compare this to a group of 3rd party judges. This will allow us to see how much consensus there is on the judging task. If maintainer judgement vary a lot from 3rd party judges, that's a strong signal that something is off.

**Comment by kronosapiens** [comment]
@JSeiferth great points. One thing I'll mention is that @ccerv1 [looked into voting behavior](https://docs.opensource.observer/blog/rf5-ballot-box/) using Pairwise and found that:

> … many of the voters who used [Pairwise] had a higher coefficient of variation than those who didn’t. This suggests that Pairwise helped voters develop more nuanced distribution preferences.

So compared to other methods, where participants experience fatigue and input simple uniform results, Pairwise helps produce expert-level decisions with much less mental burden relative to other approaches.

I also think it's worth thinking critically about the task -- assessing relative value of dependencies. I am skeptical that anything short of a professional security audit will provide the level of insight regarding dependency usage that folks are hoping for. A more realistic task IMO is to provide a side-by-side comparison and invite the user to determine, heuristically, what the relative impact would be. Assume the judge is an ecosystem developer with 3-5 years experience -- they know what `open-zeppelin` is, they know what `ethers` is, they know what `hardhat` is. With a sufficiently rich UI, a judge should be able to make a decision which is more right than wrong.

I think the process as laid out meets the goals you set -- will gather a sufficient volume to cover the subgraphs, with high quality (given the constraints of the process).

**Comment by kronosapiens** [comment]
Noting here that the approach discussed in this issue is fundamentally different from the one being developed by Vitalik and Joel, see:

[Deepfunding_Technical_Plan.pdf](https://github.com/user-attachments/files/18201324/Deepfunding_Technical_Plan.pdf)
[credit_analysis_py.txt](https://github.com/user-attachments/files/18201340/credit_analysis_py.txt)

In this issue's approach, juror submissions are turned into a credit distribution across projects (`f(j) -> x`), and used to score submissions using squared error (`|| w - x ||`). In the approach being put forward by Vitalik and Joel, juror submissions are being used to score model weights directly, by comparing juror submissions to _ratios_ of model weights.

I will admit I had not fully understood the approach they suggested until I saw the technical plan, and so much of the discussion here around gathering training data may no longer apply. Specifically, the proposed evaluation model does not seem to require the same density of juror inputs.

Happy to leave this issue open for posterity, but I don't think it is relevant to the project going forward.
